services:
  localedit:
    # GitHub Container Registry (Recommended)
    # simple mode - ghcr.io/alam00000/localedit-simple:latest
    # default mode - ghcr.io/alam00000/localedit:latest
    # Docker Hub (Alternative)
    # simple mode - localeditteam/localedit-simple:latest
    # default mode - localeditteam/localedit:latest
    image: ghcr.io/alam00000/localedit-simple:latest
    container_name: localedit
    restart: unless-stopped
    ports:
      - '8080:8080'
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
